# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: manjaro-contrib/.github
repository:
  homepage: https://aur.archlinux.org/yay-bin.git
# you can extend settings using https://probot.github.io/apps/settings/
